"""PDF Pre-Alignment Report Generator.

Uses WeasyPrint (free, open-source) to generate PDF reports.
Uses staticmap (wraps OSM tiles, no API key) for corridor map thumbnails.
"""

import logging
import uuid
from typing import Any

from sqlalchemy import select, text
from sqlalchemy.ext.asyncio import AsyncSession

from app.models.analysis import ConflictReport
from app.models.project import Project

logger = logging.getLogger(__name__)

HTML_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8"/>
<style>
  body {{ font-family: Arial, sans-serif; font-size: 11pt; margin: 2cm; color: #1a1a1a; }}
  h1 {{ color: #1a3a6e; border-bottom: 2px solid #1a3a6e; padding-bottom: 6px; }}
  h2 {{ color: #2d5fa6; margin-top: 24px; }}
  table {{ width: 100%; border-collapse: collapse; margin-top: 12px; }}
  th {{ background: #1a3a6e; color: white; padding: 8px; text-align: left; font-size: 10pt; }}
  td {{ padding: 6px 8px; border-bottom: 1px solid #ddd; font-size: 10pt; }}
  tr:nth-child(even) {{ background: #f5f8ff; }}
  .severity-blocker {{ background: #ff4d4d !important; color: white; font-weight: bold; }}
  .severity-high {{ background: #ff9933 !important; color: white; }}
  .severity-medium {{ background: #ffcc00 !important; }}
  .severity-low {{ background: #90ee90 !important; }}
  .badge {{ display: inline-block; padding: 2px 8px; border-radius: 4px; font-size: 9pt; font-weight: bold; }}
  .meta-grid {{ display: grid; grid-template-columns: 1fr 1fr; gap: 8px; }}
  .meta-item {{ background: #f0f4ff; padding: 8px; border-radius: 4px; }}
  .meta-label {{ font-size: 9pt; color: #666; }}
  .meta-value {{ font-size: 11pt; font-weight: bold; color: #1a3a6e; }}
  img.map {{ width: 100%; max-height: 300px; border: 1px solid #ccc; border-radius: 4px; }}
  .footer {{ margin-top: 48px; font-size: 9pt; color: #888; border-top: 1px solid #ccc; padding-top: 8px; }}
</style>
</head>
<body>
<h1>PM GatiShakti — Pre-Alignment Report</h1>

<h2>Project Details</h2>
<div class="meta-grid">
  <div class="meta-item"><div class="meta-label">Project Name</div><div class="meta-value">{name}</div></div>
  <div class="meta-item"><div class="meta-label">Type</div><div class="meta-value">{project_type}</div></div>
  <div class="meta-item"><div class="meta-label">Ministry</div><div class="meta-value">{ministry}</div></div>
  <div class="meta-item"><div class="meta-label">Status</div><div class="meta-value">{status}</div></div>
  <div class="meta-item"><div class="meta-label">Analysis Buffer</div><div class="meta-value">{buffer_m}m</div></div>
  <div class="meta-item"><div class="meta-label">Estimated Cost</div><div class="meta-value">{cost}</div></div>
</div>

{map_img_html}

<h2>Conflict Summary ({conflict_count} conflicts detected)</h2>
{conflicts_table}

<h2>Regulatory Clearances Required</h2>
{clearances_html}

<div class="footer">
  Generated by GatiShakti Intelligence Platform (GSIP) &mdash; {generated_at}<br/>
  Report ID: {project_id}
</div>
</body>
</html>"""


class ReportGenerator:
    """Generates PDF pre-alignment reports using WeasyPrint + staticmap."""

    def __init__(self, db: AsyncSession) -> None:
        self._db = db

    async def generate(self, project_id: uuid.UUID) -> bytes:
        """Produce a complete PDF report for the given project.

        Fetches: project metadata, conflict reports, gap analysis.
        Renders a static map thumbnail if corridor geometry exists.
        """
        project = await self._db.get(Project, project_id)
        if not project:
            raise ValueError(f"Project {project_id} not found")

        conflicts_result = await self._db.execute(
            select(ConflictReport)
            .where(ConflictReport.project_id == project_id)
            .order_by(ConflictReport.severity)
        )
        conflicts = conflicts_result.scalars().all()

        map_img_html = await self._build_map_html(project)
        conflicts_table = self._build_conflict_table(conflicts)
        clearances_html = self._build_clearances_html(conflicts)

        from datetime import datetime, timezone

        html = HTML_TEMPLATE.format(
            name=project.name,
            project_type=project.project_type or "N/A",
            ministry=project.ministry or "N/A",
            status=project.status,
            buffer_m=project.buffer_m,
            cost=f"₹{project.cost_crore:,.2f} Cr" if project.cost_crore else "N/A",
            project_id=str(project_id),
            conflict_count=len(conflicts),
            map_img_html=map_img_html,
            conflicts_table=conflicts_table,
            clearances_html=clearances_html,
            generated_at=datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC"),
        )

        return self._render_pdf(html)

    async def _build_map_html(self, project: Project) -> str:
        """Generate a static map thumbnail using staticmap (OSM tiles, no API key)."""
        if project.corridor_geom is None:
            return "<p><em>No corridor geometry available for map thumbnail.</em></p>"

        try:
            centroid_sql = text("""
                SELECT
                    ST_X(ST_Centroid(corridor_geom)) AS lon,
                    ST_Y(ST_Centroid(corridor_geom)) AS lat
                FROM projects WHERE id = :id
            """)
            result = await self._db.execute(centroid_sql, {"id": str(project.id)})
            row = result.fetchone()
            if not row:
                return ""
            lon, lat = row.lon, row.lat

            from staticmap import StaticMap, Line
            from sqlalchemy import text as sql_text

            # Get corridor as WKT to extract coordinates
            wkt_sql = sql_text("SELECT ST_AsGeoJSON(corridor_geom)::json AS geojson FROM projects WHERE id = :id")
            wkt_result = await self._db.execute(wkt_sql, {"id": str(project.id)})
            wkt_row = wkt_result.fetchone()
            if not wkt_row or not wkt_row.geojson:
                return ""

            geojson = wkt_row.geojson
            coords = geojson.get("coordinates", [])

            m = StaticMap(800, 400)
            if coords and len(coords) >= 2:
                line = Line(coords, "blue", 3)
                m.add_line(line)

            image = m.render(zoom=8, center=[lon, lat])
            import io
            import base64
            buf = io.BytesIO()
            image.save(buf, format="PNG")
            b64 = base64.b64encode(buf.getvalue()).decode()
            return f'<h2>Corridor Map</h2><img class="map" src="data:image/png;base64,{b64}" alt="Corridor Map"/>'

        except Exception as exc:
            logger.warning("Map thumbnail generation failed: %s", exc)
            return "<p><em>Map thumbnail unavailable.</em></p>"

    @staticmethod
    def _build_conflict_table(conflicts: list[ConflictReport]) -> str:
        """Render an HTML table of conflict records sorted by severity."""
        if not conflicts:
            return "<p>No conflicts detected for this corridor.</p>"

        rows = ""
        for c in conflicts:
            sev_class = f"severity-{c.severity}" if c.severity else ""
            area = f"{float(c.area_sqm):,.0f} m²" if c.area_sqm else "N/A"
            rows += (
                f"<tr>"
                f"<td><span class='badge {sev_class}'>{(c.severity or '').upper()}</span></td>"
                f"<td>{c.conflict_type or 'unknown'}</td>"
                f"<td>{area}</td>"
                f"<td>{c.description or ''}</td>"
                f"</tr>"
            )

        return f"""
        <table>
          <thead><tr><th>Severity</th><th>Conflict Type</th><th>Area</th><th>Description</th></tr></thead>
          <tbody>{rows}</tbody>
        </table>"""

    @staticmethod
    def _build_clearances_html(conflicts: list[ConflictReport]) -> str:
        """Map detected conflict types to required regulatory clearances."""
        clearance_map: dict[str, str] = {
            "protected_forest": "Forest Clearance (FC) — Forest Conservation Act 1980",
            "wildlife_sanctuary": "Wildlife Clearance — Wildlife Protection Act 1972",
            "national_park": "Wildlife Clearance + Stage-I Forest Clearance",
            "crz_zone_1": "CRZ Clearance from MoEFCC — Coastal Regulation Zone 2019",
            "crz_zone_2": "CRZ Clearance from State Coastal Zone Management Authority",
            "crz_zone_3": "CRZ NOC from District Authority",
            "wetland_ramsar": "Wetland Clearance — Wetlands (Conservation and Management) Rules 2017",
            "eco_sensitive": "Environmental Clearance (EC) — EIA Notification 2006",
            "heritage_buffer": "NOC from Archaeological Survey of India",
            "river": "NOC from Central Water Commission + State Irrigation Dept",
        }

        conflict_types = {c.conflict_type for c in conflicts if c.conflict_type}
        required = [
            f"<li>{clearance_map[ct]}</li>"
            for ct in conflict_types
            if ct in clearance_map
        ]

        if not required:
            return "<p>No specific regulatory clearances identified. Standard NOCs apply.</p>"

        return f"<ul>{''.join(required)}</ul>"

    @staticmethod
    def _render_pdf(html: str) -> bytes:
        """Render HTML to PDF bytes using WeasyPrint."""
        from weasyprint import HTML as WeasyHTML

        doc = WeasyHTML(string=html)
        return doc.write_pdf()
