apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    uid: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: false

dashboards:
  - name: GSIP Dashboards
    type: file
    options:
      path: /etc/grafana/provisioning/dashboards
    disableDeletion: true
    updateIntervalSeconds: 30
